[package]
name = "poll"
version = "0.1.0"
edition = "2021"

default-run = "poll"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.150"
